// aridan.net
// lyricsEasterEggScript.js
// The actual words for the "Look What You Made Me Do" easter egg lyrics video.
// This is the only file you should need to touch to add/change lines.
//
// Format — one row per line:
//   m:ss "the words for this row"
//
// Rules:
//   - Timestamp is minutes:seconds into the track (song is 3:32 / 212s long).
//   - A blank line starts a new phrase: the screen clears before the next
//     line pops in. Group your rows into short phrases separated by blank lines.
//   - Wrap a word in *asterisks* to color it (the "emphasis" look).
//   - Wrap a word in _underscores_ to underline it.
//   - Lines starting with # are comments and are ignored, same as blank lines
//     (but comments don't start a new phrase).
//
// Example:
//   2:21 "sweetheart"
//   2:22 "not again"
//
// See lyricsEasterEgg.js for the parser/player — you shouldn't need to touch that.

window.LYRICS_EASTER_EGG_SCRIPT = `
0:00 "⋅⋅⋅"

0:15 "I"

0:16 "DON'T"
0:16 "LIKE YOUR LITTLE ADS"

0:20 "DON'T"
0:20 "LIKE YOUR TITLED TELEMETRY"

0:23 "THE ROLE YOU MADE ME PLAY"

0:27 "OF THE FOOL, NO I DON'T LIKE YOU"

0:30 "I DON'T"
0:30 "LIKE YOUR PERFECT CRIME"

0:34 "HOW"
0:34 "YOU LAUGH WHEN YOU TRACK"

0:38 "YOU"
0:38 "SAID THE BLAME WAS MINE"

0:42 "ISN'T COOL"
0:42 "NO, I DON'T LIKE YOU"

0:45 "BUT I GOT SMARTER"
0:45 "I BLOCK YOUR DOMAIN IN THE NICK OF TIME"

0:49 "HONEY, I CIRCUMVENTED YOUR PAYWALL"
0:49 "I DO IT ALL THE TIME"

0:53 "I GOT A LIST OF DOMAINS"
0:54 "AND YOURS IS IN *RED*"
0:55 "_UNDERLINED_"

0:57 "I CHECK IT ONCE"
0:58 "THEN I CHECK IT *TWICE*"
0:59 "OH!"

1:00 "OH, LOOK WHAT YOU MADE ME BLOCK"

1:03 "LOOK WHAT YOU MADE ME BLOCK"

1:05 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

1:06 "LOOK WHAT YOU JUST MADE ME"

1:08 "OH, LOOK WHAT YOU MADE ME BLOCK"

1:10 "LOOK WHAT YOU MADE ME BLOCK"

1:12 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

1:14 "LOOK WHAT YOU JUST MADE ME BLOCK"

1:15 "I DON'T"
1:15 "LIKE YOUR AD REVENUE"

1:19 "THE INTERENT"
1:19 "ONCE BELONGED TO ME"

1:24 "YOU"
1:24 "ASK ME FOR A PLACE TO SLEEP"

1:27 "LOCKED ME OUT"
1:27 "AND THREW A FEAST"
1:29 "_WHAT?_"

1:30 "THE WORLD MOVES ON"
1:30 "ANOTHER DAY"
1:32 "ANOTHER AD, AD"

1:34 "BUT NOT ME FOR ME, NOT FOR ME"
1:36 "ALL I THINK ABOUT IS"
1:37 "KARMA"

1:38 "AND THEN THE WORLD ACCEPTS IT"
1:38 "BUT ONE THING'S FOR SURE"

1:41 "MAYBE I GOT MINE"
1:41 "BUT YOU SHOULD ALL GET YOURS"

1:45 "BUT I GOT SMARTER"
1:45 "I BLOCK YOUR DOMAIN IN THE NICK OF TIME"

1:49 "HONEY, I CIRCUMVENTED YOUR PAYWALL"
1:49 "I DO IT ALL THE TIME"

1:53 "I GOT A LIST OF DOMAINS"
1:54 "AND YOURS IS IN *RED*"
1:55 "_UNDERLINED_"

1:57 "I CHECK IT ONCE"
1:58 "THEN I CHECK IT *TWICE*"
1:59 "OH!"

2:00 "OH, LOOK WHAT YOU MADE ME BLOCK"

2:03 "LOOK WHAT YOU MADE ME BLOCK"

2:05 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

2:06 "LOOK WHAT YOU JUST MADE ME"

2:08 "OH, LOOK WHAT YOU MADE ME BLOCK"

2:10 "LOOK WHAT YOU MADE ME BLOCK"

2:12 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

2:14 "LOOK WHAT YOU JUST MADE ME BLOCK"

2:15 "I DON'T TRUST NOBODY"
2:15 "AND NOBODY TRUSTS ME"

2:19 "I'LL BE THE *FAILED*"
2:19 "ALL UP IN YOUR LOGS"

2:22 "I DON'T TRUST NOBODY"
2:22 "AND NOBODY TRUSTS ME"

2:26 "I'LL BE THE *FAILED*"
2:26 "ALL UP IN YOUR LOGS"

2:30 "I DON'T TRUST NOBODY"
2:30 "AND NOBODY TRUSTS ME"

2:34 "I'LL BE THE *FAILED*"
2:34 "ALL UP IN YOUR LOGS"

2:38 "I DON'T TRUST NOBODY"
2:38 "AND NOBODY TRUSTS ME"

2:42 "I'LL BE THE *FAILED*"
2:42 "ALL UP _IN YOUR LOGS_"

2:45 "⋅⋅⋅"

2:51 "I'M SORRY."
2:52 "THE AD SERVER CAN'T COME TO THE PHONE RIGHT NOW."

2:56 "WHY?"
2:57 "OH."
2:59 "'CAUSE IT'S *DEAD*."

3:00 "OH, LOOK WHAT YOU MADE ME BLOCK"

3:03 "LOOK WHAT YOU MADE ME BLOCK"

3:05 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

3:06 "LOOK WHAT YOU JUST MADE ME"

3:08 "OH, LOOK WHAT YOU MADE ME BLOCK"

3:10 "LOOK WHAT YOU MADE ME BLOCK"

3:12 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

3:14 "LOOK WHAT YOU JUST MADE ME BLOCK"


3:15 "OH, LOOK WHAT YOU MADE ME BLOCK"

3:17 "LOOK WHAT YOU MADE ME BLOCK"

3:20 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

3:22 "LOOK WHAT YOU JUST MADE ME"

3:23 "OH, LOOK WHAT YOU MADE ME BLOCK"

3:25 "LOOK WHAT YOU MADE ME BLOCK"

3:27 "LOOK WHAT *YOU* JUST MADE ME BLOCK"

3:29 "LOOK WHAT YOU JUST MADE ME BLOCK"

3:31 ""
`;
